### ISSUE TITLE
Feature Request: Support for one-way control

### ISSUE THREAD

**Issue by b0o** [feschber/lan-mouse#164]
Really awesome project! One thing that would be nice is that I want to control my Mac from my Linux computer, but not the other way around. When I am focused on my Linux computer, I don't want my Mac's trackpad to be routed to my Linux computer. I always want the trackpad to control my Mac.

Maybe something like this in the config:

```toml
[right]
hostname = "my_mac"
activate_on_startup = true
client_only = true
```

(Note: I am currently using #131 on my Mac)
