### ISSUE TITLE
Config not working/clients not loaded?

### ISSUE THREAD

**Issue by Delivator** [feschber/lan-mouse#296]
I created a config file as per the example in the readme, and the startup log shows me that the config file has been loaded but the client I have added are just not there, I still have to manually add them. I have double checked that the IP and hostname are correct.

This is my config:

```toml
[[clients]]
# position (left | right | top | bottom)
position = "left"
# hostname
hostname = "pc1"
# activate this client immediately when lan-mouse is started
activate_on_startup = true
# optional list of (known) ip addresses
ips = ["192.168.178.XX"]

```
